/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ActivityCategory = IDL.Variant({
  'event' : IDL.Null,
  'training' : IDL.Null,
});
export const Id = IDL.Nat;
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TeamRole = IDL.Variant({
  'senior' : IDL.Null,
  'trainer' : IDL.Null,
  'leadership' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ActivityCategory,
});
export const AdmissionFees = IDL.Record({
  'admission' : IDL.Nat,
  'monthly' : IDL.Nat,
});
export const AdmissionInfo = IDL.Record({
  'documents' : IDL.Vec(IDL.Text),
  'fees' : AdmissionFees,
});
export const Branch = IDL.Record({
  'id' : Id,
  'isHQ' : IDL.Bool,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Camp = IDL.Record({
  'id' : Id,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'activities' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'isActive' : IDL.Bool,
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'mediaType' : MediaType,
  'uploadedAt' : Timestamp,
});
export const OrgInfo = IDL.Record({
  'affiliationNo' : IDL.Text,
  'mission' : IDL.Vec(IDL.Text),
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'logoBlob' : IDL.Opt(ExternalBlob),
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'registrationNo' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : Id,
  'photoBlob' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'role' : TeamRole,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addActivity' : IDL.Func([IDL.Text, IDL.Text, ActivityCategory], [Id], []),
  'addBranch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Id],
      [],
    ),
  'addCamp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Id],
      [],
    ),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, MediaType, ExternalBlob, IDL.Opt(ExternalBlob)],
      [Id],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, TeamRole, IDL.Opt(ExternalBlob), IDL.Nat],
      [Id],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteActivity' : IDL.Func([Id], [], []),
  'deleteBranch' : IDL.Func([Id], [], []),
  'deleteGalleryItem' : IDL.Func([Id], [], []),
  'deleteTeamMember' : IDL.Func([Id], [], []),
  'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAdmissionInfo' : IDL.Func([], [IDL.Opt(AdmissionInfo)], ['query']),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCamps' : IDL.Func([], [IDL.Vec(Camp)], ['query']),
  'getContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getOrgInfo' : IDL.Func([], [IDL.Opt(OrgInfo)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactRead' : IDL.Func([Id], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Id], []),
  'updateActivity' : IDL.Func(
      [Id, IDL.Text, IDL.Text, ActivityCategory],
      [],
      [],
    ),
  'updateAdmissionInfo' : IDL.Func([AdmissionInfo], [], []),
  'updateBranch' : IDL.Func(
      [Id, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateCamp' : IDL.Func(
      [Id, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateOrgInfo' : IDL.Func([OrgInfo], [], []),
  'updateOrgLogo' : IDL.Func([ExternalBlob], [], []),
  'updateTeamMember' : IDL.Func(
      [Id, IDL.Text, IDL.Text, TeamRole, IDL.Opt(ExternalBlob), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ActivityCategory = IDL.Variant({
    'event' : IDL.Null,
    'training' : IDL.Null,
  });
  const Id = IDL.Nat;
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TeamRole = IDL.Variant({
    'senior' : IDL.Null,
    'trainer' : IDL.Null,
    'leadership' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ActivityCategory,
  });
  const AdmissionFees = IDL.Record({
    'admission' : IDL.Nat,
    'monthly' : IDL.Nat,
  });
  const AdmissionInfo = IDL.Record({
    'documents' : IDL.Vec(IDL.Text),
    'fees' : AdmissionFees,
  });
  const Branch = IDL.Record({
    'id' : Id,
    'isHQ' : IDL.Bool,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Camp = IDL.Record({
    'id' : Id,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'activities' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'isActive' : IDL.Bool,
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'mediaType' : MediaType,
    'uploadedAt' : Timestamp,
  });
  const OrgInfo = IDL.Record({
    'affiliationNo' : IDL.Text,
    'mission' : IDL.Vec(IDL.Text),
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'logoBlob' : IDL.Opt(ExternalBlob),
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'registrationNo' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : Id,
    'photoBlob' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'role' : TeamRole,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addActivity' : IDL.Func([IDL.Text, IDL.Text, ActivityCategory], [Id], []),
    'addBranch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Id],
        [],
      ),
    'addCamp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Id],
        [],
      ),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, MediaType, ExternalBlob, IDL.Opt(ExternalBlob)],
        [Id],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, TeamRole, IDL.Opt(ExternalBlob), IDL.Nat],
        [Id],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteActivity' : IDL.Func([Id], [], []),
    'deleteBranch' : IDL.Func([Id], [], []),
    'deleteGalleryItem' : IDL.Func([Id], [], []),
    'deleteTeamMember' : IDL.Func([Id], [], []),
    'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAdmissionInfo' : IDL.Func([], [IDL.Opt(AdmissionInfo)], ['query']),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCamps' : IDL.Func([], [IDL.Vec(Camp)], ['query']),
    'getContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getOrgInfo' : IDL.Func([], [IDL.Opt(OrgInfo)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactRead' : IDL.Func([Id], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Id], []),
    'updateActivity' : IDL.Func(
        [Id, IDL.Text, IDL.Text, ActivityCategory],
        [],
        [],
      ),
    'updateAdmissionInfo' : IDL.Func([AdmissionInfo], [], []),
    'updateBranch' : IDL.Func(
        [Id, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateCamp' : IDL.Func(
        [Id, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateOrgInfo' : IDL.Func([OrgInfo], [], []),
    'updateOrgLogo' : IDL.Func([ExternalBlob], [], []),
    'updateTeamMember' : IDL.Func(
        [Id, IDL.Text, IDL.Text, TeamRole, IDL.Opt(ExternalBlob), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };