/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : Id,
  'name' : string,
  'description' : string,
  'category' : ActivityCategory,
}
export type ActivityCategory = { 'event' : null } |
  { 'training' : null };
export interface AdmissionFees { 'admission' : bigint, 'monthly' : bigint }
export interface AdmissionInfo {
  'documents' : Array<string>,
  'fees' : AdmissionFees,
}
export interface Branch {
  'id' : Id,
  'isHQ' : boolean,
  'name' : string,
  'contactPerson' : string,
  'address' : string,
  'phone' : string,
}
export interface Camp {
  'id' : Id,
  'duration' : string,
  'name' : string,
  'activities' : Array<string>,
  'description' : string,
}
export interface ContactSubmission {
  'id' : Id,
  'name' : string,
  'submittedAt' : Timestamp,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : Id,
  'title' : string,
  'blob' : ExternalBlob,
  'isActive' : boolean,
  'thumbnailBlob' : [] | [ExternalBlob],
  'mediaType' : MediaType,
  'uploadedAt' : Timestamp,
}
export type Id = bigint;
export type MediaType = { 'video' : null } |
  { 'photo' : null };
export interface OrgInfo {
  'affiliationNo' : string,
  'mission' : Array<string>,
  'tagline' : string,
  'name' : string,
  'logoBlob' : [] | [ExternalBlob],
  'email' : string,
  'address' : string,
  'phone' : string,
  'department' : string,
  'registrationNo' : string,
}
export interface TeamMember {
  'id' : Id,
  'photoBlob' : [] | [ExternalBlob],
  'title' : string,
  'order' : bigint,
  'name' : string,
  'role' : TeamRole,
}
export type TeamRole = { 'senior' : null } |
  { 'trainer' : null } |
  { 'leadership' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addActivity' : ActorMethod<[string, string, ActivityCategory], Id>,
  'addBranch' : ActorMethod<[string, string, string, string, boolean], Id>,
  'addCamp' : ActorMethod<[string, string, string, Array<string>], Id>,
  'addGalleryItem' : ActorMethod<
    [string, MediaType, ExternalBlob, [] | [ExternalBlob]],
    Id
  >,
  'addTeamMember' : ActorMethod<
    [string, string, TeamRole, [] | [ExternalBlob], bigint],
    Id
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteActivity' : ActorMethod<[Id], undefined>,
  'deleteBranch' : ActorMethod<[Id], undefined>,
  'deleteGalleryItem' : ActorMethod<[Id], undefined>,
  'deleteTeamMember' : ActorMethod<[Id], undefined>,
  'getActivities' : ActorMethod<[], Array<Activity>>,
  'getAdmissionInfo' : ActorMethod<[], [] | [AdmissionInfo]>,
  'getBranches' : ActorMethod<[], Array<Branch>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCamps' : ActorMethod<[], Array<Camp>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getOrgInfo' : ActorMethod<[], [] | [OrgInfo]>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markContactRead' : ActorMethod<[Id], undefined>,
  'submitContact' : ActorMethod<[string, string, string], Id>,
  'updateActivity' : ActorMethod<
    [Id, string, string, ActivityCategory],
    undefined
  >,
  'updateAdmissionInfo' : ActorMethod<[AdmissionInfo], undefined>,
  'updateBranch' : ActorMethod<
    [Id, string, string, string, string, boolean],
    undefined
  >,
  'updateCamp' : ActorMethod<
    [Id, string, string, string, Array<string>],
    undefined
  >,
  'updateOrgInfo' : ActorMethod<[OrgInfo], undefined>,
  'updateOrgLogo' : ActorMethod<[ExternalBlob], undefined>,
  'updateTeamMember' : ActorMethod<
    [Id, string, string, TeamRole, [] | [ExternalBlob], bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];