/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdmissionInfo {
    documents: Array<string>;
    fees: AdmissionFees;
}
export type Timestamp = bigint;
export interface OrgInfo {
    affiliationNo: string;
    mission: Array<string>;
    tagline: string;
    name: string;
    logoBlob?: ExternalBlob;
    email: string;
    address: string;
    phone: string;
    department: string;
    registrationNo: string;
}
export interface ContactSubmission {
    id: Id;
    name: string;
    submittedAt: Timestamp;
    isRead: boolean;
    email: string;
    message: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Activity {
    id: Id;
    name: string;
    description: string;
    category: ActivityCategory;
}
export type Id = bigint;
export interface Branch {
    id: Id;
    isHQ: boolean;
    name: string;
    contactPerson: string;
    address: string;
    phone: string;
}
export interface TeamMember {
    id: Id;
    photoBlob?: ExternalBlob;
    title: string;
    order: bigint;
    name: string;
    role: TeamRole;
}
export interface AdmissionFees {
    admission: bigint;
    monthly: bigint;
}
export interface Camp {
    id: Id;
    duration: string;
    name: string;
    activities: Array<string>;
    description: string;
}
export interface GalleryItem {
    id: Id;
    title: string;
    blob: ExternalBlob;
    isActive: boolean;
    thumbnailBlob?: ExternalBlob;
    mediaType: MediaType;
    uploadedAt: Timestamp;
}
export enum ActivityCategory {
    event = "event",
    training = "training"
}
export enum MediaType {
    video = "video",
    photo = "photo"
}
export enum TeamRole {
    senior = "senior",
    trainer = "trainer",
    leadership = "leadership"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addActivity(name: string, description: string, category: ActivityCategory): Promise<Id>;
    addBranch(name: string, address: string, contactPerson: string, phone: string, isHQ: boolean): Promise<Id>;
    addCamp(name: string, duration: string, description: string, campActivities: Array<string>): Promise<Id>;
    addGalleryItem(title: string, mediaType: MediaType, blob: ExternalBlob, thumbnailBlob: ExternalBlob | null): Promise<Id>;
    addTeamMember(name: string, title: string, role: TeamRole, photoBlob: ExternalBlob | null, order: bigint): Promise<Id>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteActivity(id: Id): Promise<void>;
    deleteBranch(id: Id): Promise<void>;
    deleteGalleryItem(id: Id): Promise<void>;
    deleteTeamMember(id: Id): Promise<void>;
    getActivities(): Promise<Array<Activity>>;
    getAdmissionInfo(): Promise<AdmissionInfo | null>;
    getBranches(): Promise<Array<Branch>>;
    getCallerUserRole(): Promise<UserRole>;
    getCamps(): Promise<Array<Camp>>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getGalleryItems(): Promise<Array<GalleryItem>>;
    getOrgInfo(): Promise<OrgInfo | null>;
    getTeamMembers(): Promise<Array<TeamMember>>;
    isCallerAdmin(): Promise<boolean>;
    markContactRead(id: Id): Promise<void>;
    submitContact(name: string, email: string, message: string): Promise<Id>;
    updateActivity(id: Id, name: string, description: string, category: ActivityCategory): Promise<void>;
    updateAdmissionInfo(info: AdmissionInfo): Promise<void>;
    updateBranch(id: Id, name: string, address: string, contactPerson: string, phone: string, isHQ: boolean): Promise<void>;
    updateCamp(id: Id, name: string, duration: string, description: string, campActivities: Array<string>): Promise<void>;
    updateOrgInfo(info: OrgInfo): Promise<void>;
    updateOrgLogo(blob: ExternalBlob): Promise<void>;
    updateTeamMember(id: Id, name: string, title: string, role: TeamRole, photoBlob: ExternalBlob | null, order: bigint): Promise<void>;
}
import type { Activity as _Activity, ActivityCategory as _ActivityCategory, AdmissionInfo as _AdmissionInfo, ExternalBlob as _ExternalBlob, GalleryItem as _GalleryItem, Id as _Id, MediaType as _MediaType, OrgInfo as _OrgInfo, TeamMember as _TeamMember, TeamRole as _TeamRole, Timestamp as _Timestamp, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addActivity(arg0: string, arg1: string, arg2: ActivityCategory): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, arg1, to_candid_ActivityCategory_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, arg1, to_candid_ActivityCategory_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addBranch(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addBranch(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBranch(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addCamp(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addCamp(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCamp(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: MediaType, arg2: ExternalBlob, arg3: ExternalBlob | null): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, to_candid_MediaType_n10(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, to_candid_MediaType_n10(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addTeamMember(arg0: string, arg1: string, arg2: TeamRole, arg3: ExternalBlob | null, arg4: bigint): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamMember(arg0, arg1, to_candid_TeamRole_n14(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamMember(arg0, arg1, to_candid_TeamRole_n14(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteActivity(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async deleteBranch(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBranch(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async deleteTeamMember(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeamMember(arg0);
            return result;
        }
    }
    async getActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdmissionInfo(): Promise<AdmissionInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmissionInfo();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmissionInfo();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBranches(): Promise<Array<Branch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBranches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBranches();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCamps(): Promise<Array<Camp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCamps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCamps();
            return result;
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItems();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItems();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrgInfo(): Promise<OrgInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrgInfo();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrgInfo();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembers();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembers();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markContactRead(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactRead(arg0);
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2);
            return result;
        }
    }
    async updateActivity(arg0: Id, arg1: string, arg2: string, arg3: ActivityCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, arg1, arg2, to_candid_ActivityCategory_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, arg1, arg2, to_candid_ActivityCategory_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateAdmissionInfo(arg0: AdmissionInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdmissionInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdmissionInfo(arg0);
            return result;
        }
    }
    async updateBranch(arg0: Id, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBranch(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBranch(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateCamp(arg0: Id, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCamp(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCamp(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateOrgInfo(arg0: OrgInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrgInfo(await to_candid_OrgInfo_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrgInfo(await to_candid_OrgInfo_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrgLogo(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrgLogo(await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrgLogo(await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTeamMember(arg0: Id, arg1: string, arg2: string, arg3: TeamRole, arg4: ExternalBlob | null, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMember(arg0, arg1, arg2, to_candid_TeamRole_n14(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMember(arg0, arg1, arg2, to_candid_TeamRole_n14(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
}
function from_candid_ActivityCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityCategory): ActivityCategory {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryItem_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_OrgInfo_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrgInfo): Promise<OrgInfo> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_TeamMember_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMember): Promise<TeamMember> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TeamRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamRole): TeamRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdmissionInfo]): AdmissionInfo | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrgInfo]): Promise<OrgInfo | null> {
    return value.length === 0 ? null : await from_candid_OrgInfo_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    name: string;
    description: string;
    category: _ActivityCategory;
}): {
    id: Id;
    name: string;
    description: string;
    category: ActivityCategory;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        category: from_candid_ActivityCategory_n21(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    blob: _ExternalBlob;
    isActive: boolean;
    thumbnailBlob: [] | [_ExternalBlob];
    mediaType: _MediaType;
    uploadedAt: _Timestamp;
}): Promise<{
    id: Id;
    title: string;
    blob: ExternalBlob;
    isActive: boolean;
    thumbnailBlob?: ExternalBlob;
    mediaType: MediaType;
    uploadedAt: Timestamp;
}> {
    return {
        id: value.id,
        title: value.title,
        blob: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.blob),
        isActive: value.isActive,
        thumbnailBlob: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.thumbnailBlob)),
        mediaType: from_candid_MediaType_n31(_uploadFile, _downloadFile, value.mediaType),
        uploadedAt: value.uploadedAt
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    affiliationNo: string;
    mission: Array<string>;
    tagline: string;
    name: string;
    logoBlob: [] | [_ExternalBlob];
    email: string;
    address: string;
    phone: string;
    department: string;
    registrationNo: string;
}): Promise<{
    affiliationNo: string;
    mission: Array<string>;
    tagline: string;
    name: string;
    logoBlob?: ExternalBlob;
    email: string;
    address: string;
    phone: string;
    department: string;
    registrationNo: string;
}> {
    return {
        affiliationNo: value.affiliationNo,
        mission: value.mission,
        tagline: value.tagline,
        name: value.name,
        logoBlob: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.logoBlob)),
        email: value.email,
        address: value.address,
        phone: value.phone,
        department: value.department,
        registrationNo: value.registrationNo
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    photoBlob: [] | [_ExternalBlob];
    title: string;
    order: bigint;
    name: string;
    role: _TeamRole;
}): Promise<{
    id: Id;
    photoBlob?: ExternalBlob;
    title: string;
    order: bigint;
    name: string;
    role: TeamRole;
}> {
    return {
        id: value.id,
        photoBlob: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.photoBlob)),
        title: value.title,
        order: value.order,
        name: value.name,
        role: from_candid_TeamRole_n39(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    event: null;
} | {
    training: null;
}): ActivityCategory {
    return "event" in value ? ActivityCategory.event : "training" in value ? ActivityCategory.training : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    photo: null;
}): MediaType {
    return "video" in value ? MediaType.video : "photo" in value ? MediaType.photo : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    senior: null;
} | {
    trainer: null;
} | {
    leadership: null;
}): TeamRole {
    return "senior" in value ? TeamRole.senior : "trainer" in value ? TeamRole.trainer : "leadership" in value ? TeamRole.leadership : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n19(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamMember>): Promise<Array<TeamMember>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TeamMember_n37(_uploadFile, _downloadFile, x)));
}
function to_candid_ActivityCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityCategory): _ActivityCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MediaType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_OrgInfo_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrgInfo): Promise<_OrgInfo> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_TeamRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamRole): _TeamRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    affiliationNo: string;
    mission: Array<string>;
    tagline: string;
    name: string;
    logoBlob?: ExternalBlob;
    email: string;
    address: string;
    phone: string;
    department: string;
    registrationNo: string;
}): Promise<{
    affiliationNo: string;
    mission: Array<string>;
    tagline: string;
    name: string;
    logoBlob: [] | [_ExternalBlob];
    email: string;
    address: string;
    phone: string;
    department: string;
    registrationNo: string;
}> {
    return {
        affiliationNo: value.affiliationNo,
        mission: value.mission,
        tagline: value.tagline,
        name: value.name,
        logoBlob: value.logoBlob ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.logoBlob)) : candid_none(),
        email: value.email,
        address: value.address,
        phone: value.phone,
        department: value.department,
        registrationNo: value.registrationNo
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    video: null;
} | {
    photo: null;
} {
    return value == MediaType.video ? {
        video: null
    } : value == MediaType.photo ? {
        photo: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamRole): {
    senior: null;
} | {
    trainer: null;
} | {
    leadership: null;
} {
    return value == TeamRole.senior ? {
        senior: null
    } : value == TeamRole.trainer ? {
        trainer: null
    } : value == TeamRole.leadership ? {
        leadership: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityCategory): {
    event: null;
} | {
    training: null;
} {
    return value == ActivityCategory.event ? {
        event: null
    } : value == ActivityCategory.training ? {
        training: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
